'use strict';var aa;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(ba(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ha=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function p(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ea=b.prototype}function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
function na(){this.o=!1;this.j=null;this.h=void 0;this.g=1;this.v=this.i=0;this.m=null}function oa(a){if(a.o)throw new TypeError("Generator is already running");a.o=!0}na.prototype.u=function(a){this.h=a};function pa(a,b){a.m={W:b,isException:!0};a.g=a.i||a.v}na.prototype.return=function(a){this.m={return:a};this.g=this.v};function r(a,b,c){a.g=c;return{value:b}}function qa(a,b){a.g=b;a.i=0}function ra(a){a.i=0;var b=a.m.W;a.m=null;return b}function sa(a){this.g=new na;this.h=a}
function ta(a,b){oa(a.g);var c=a.g.j;if(c)return ua(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return va(a)}function ua(a,b,c,d){try{var e=b.call(a.g.j,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.o=!1,e;var f=e.value}catch(g){return a.g.j=null,pa(a.g,g),va(a)}a.g.j=null;d.call(a.g,f);return va(a)}
function va(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.o=!1,{value:b.value,done:!1}}catch(c){a.g.h=void 0,pa(a.g,c)}a.g.o=!1;if(a.g.m){b=a.g.m;a.g.m=null;if(b.isException)throw b.W;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function wa(a){this.next=function(b){oa(a.g);a.g.j?b=ua(a,a.g.j.next,b,a.g.u):(a.g.u(b),b=va(a));return b};this.throw=function(b){oa(a.g);a.g.j?b=ua(a,a.g.j["throw"],b,a.g.u):(pa(a.g,b),b=va(a));return b};this.return=function(b){return ta(a,b)};this[Symbol.iterator]=function(){return this}}function xa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return xa(new wa(new sa(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ma?function(b,c){try{return ma(b,c),!0}catch(d){return!1}}:null});
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.C),reject:g(this.m)}};b.prototype.C=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.G(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.B(g):this.o(g)}};
b.prototype.B=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.H(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.F();this.D()};b.prototype.F=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.D=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.G=function(g){var h=this.j();g.K(h.resolve,h.reject)};b.prototype.H=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(x,z){return typeof x=="function"?function(G){try{m(x(G))}catch(C){n(C)}}:z}var m,n,w=new b(function(x,z){m=x;n=z});this.K(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.K=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).K(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(G){return function(C){x[G]=C;z--;z==0&&m(x)}}var x=[],z=0;do x.push(void 0),z++,d(k.value).K(w(x.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ma});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ya=typeof Object.assign=="function"?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||ya});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return fa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Aa=this||self;function Ba(a){a:{var b=["CLOSURE_FLAGS"];for(var c=Aa,d=0;d<b.length;d++)if(c=c[b[d]],c==null){b=null;break a}b=c}a=b&&b[a];return a!=null?a:!1}function Ca(a){return a};var Da=Ba(610401301),Ea=Ba(748402147);function Fa(){return typeof BigInt==="function"};var Ga=typeof Aa.BigInt==="function"&&typeof Aa.BigInt(0)==="bigint";var Ha=Number.MIN_SAFE_INTEGER.toString(),Ia=Ga?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ja=Number.MAX_SAFE_INTEGER.toString(),Ka=Ga?BigInt(Number.MAX_SAFE_INTEGER):void 0;function La(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ma=typeof Uint8Array.prototype.slice==="function",v=0,y=0,Na;function Oa(a){var b=a>>>0;v=b;y=(a-b)/4294967296>>>0}function Pa(a){if(a<0){Oa(-a);var b=q(Qa(v,y));a=b.next().value;b=b.next().value;v=a>>>0;y=b>>>0}else Oa(a)}function Ra(a){var b=Na||(Na=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;v=b.getUint32(0,!0)}function Sa(a){var b=Na||(Na=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function Ta(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:Ua(a,b)}function Va(a,b){var c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=Ta(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a}
function Ua(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Fa()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+Wa(c)+Wa(a));return c}function Wa(a){a=String(a);return"0000000".slice(a.length)+a}
function Xa(a){if(a.length<16)Pa(Number(a));else if(Fa())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,v=v*1E6+d,v>=4294967296&&(y+=Math.trunc(v/4294967296),y>>>=0,v>>>=0);b&&(b=q(Qa(v,y)),a=b.next().value,b=b.next().value,v=a,y=b)}}function Qa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function Ya(a,b){this.h=a>>>0;this.g=b>>>0}function Za(a){return a.h===0?new Ya(0,1+~a.g):new Ya(~a.h+1,~a.g)}function $a(a){a=BigInt.asUintN(64,a);return new Ya(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function ab(a){if(!a)return bb||(bb=new Ya(0,0));if(!/^\d+$/.test(a))return null;Xa(a);return new Ya(v,y)}var bb;function cb(a,b){this.h=a>>>0;this.g=b>>>0}function db(a){a=BigInt.asUintN(64,a);return new cb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}
function eb(a){if(!a)return fb||(fb=new cb(0,0));if(!/^-?\d+$/.test(a))return null;Xa(a);return new cb(v,y)}var fb;function gb(a,b){return Error("Invalid wire type: "+a+" (at position "+b+")")}function hb(){return Error("Failed to read varint, encoding is invalid.")}function ib(a,b){return Error("Tried to read past the end of the data "+b+" > "+a)};function jb(){throw Error("Invalid UTF8");}function kb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var lb=void 0,mb,nb=typeof TextDecoder!=="undefined",ob,pb=typeof String.prototype.isWellFormed==="function",qb=typeof TextEncoder!=="undefined";
function rb(a){var b=!1;b=b===void 0?!1:b;if(qb){if(b&&(pb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(ob||(ob=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function sb(a){Aa.setTimeout(function(){throw a;},0)};function tb(){var a=Aa.navigator;return a&&(a=a.userAgent)?a:""}var ub,vb=Aa.navigator;ub=vb?vb.userAgentData||null:null;var wb={},xb=null;function yb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;zb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function zb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=xb[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Ab();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Ab(){if(!xb){xb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));wb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];xb[f]===void 0&&(xb[f]=e)}}}};var Bb=typeof Uint8Array!=="undefined",Cb=!(Da&&ub&&ub.brands.length>0?0:tb().indexOf("Trident")!=-1||tb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Db=/[-_.]/g,Eb={"-":"+",_:"/",".":"="};function Fb(a){return Eb[a]||""}function Gb(a){if(!Cb)return yb(a);a=Db.test(a)?a.replace(Db,Fb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Hb={};function Ib(a,b){Jb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Kb(){return Mb||(Mb=new Ib(null,Hb))}function Nb(a){Jb(Hb);var b=a.g;b=b==null||Bb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Gb(b):null;return b==null?b:a.g=b}var Mb;function Jb(a){if(a!==Hb)throw Error("illegal external caller");};function Ob(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function Pb(a,b){if(typeof a==="string")return new Ob(Gb(a),b);if(Array.isArray(a))return new Ob(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Ob(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Ob(a,!1);if(a.constructor===Ib)return b=Nb(a)||new Uint8Array(0),new Ob(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Ob(a,!1);throw Error();};function Qb(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.init(a,b,c,d)}Qb.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.J===void 0?!1:e.J;e=e.L===void 0?!1:e.L;this.J=d;this.L=e;a&&(a=Pb(a,this.L),this.h=a.buffer,this.m=a.g,this.j=b||0,this.i=c!==void 0?this.j+c:this.h.length,this.g=this.j)};Qb.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.J=!1};
function Rb(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);e>32&&(d|=(h&127)>>4);for(e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Sb(a,g);if(h<128)return b(c>>>0,d>>>0);throw hb();}function Sb(a,b){a.g=b;if(b>a.i)throw ib(a.i,b);}
function Tb(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw hb();Sb(a,c);return e}function Ub(a){return Tb(a)>>>0}function Vb(a){a=Ub(a);return a>>>1^-(a&1)}function Wb(a){return Rb(a,Va)}function Xb(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Sb(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function Yb(a){var b=Xb(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function Zb(a){var b=Xb(a),c=Xb(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function $b(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Sb(a,c),!!(b&127)}throw hb();}function ac(a){return Tb(a)}
function bc(a,b){if(b<0)throw Error("Tried to read a negative byte length: "+b);var c=a.g,d=c+b;if(d>a.i)throw ib(b,a.i-c);a.g=d;return c}function cc(a,b){if(b==0)return Kb();var c=bc(a,b);a.J&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Ma?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Kb():new Ib(c,Hb)}var dc=[],ec=void 0;function fc(){this.g=[]}fc.prototype.length=function(){return this.g.length};fc.prototype.end=function(){var a=this.g;this.g=[];return a};function hc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function ic(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function jc(a,b){if(b>=0)ic(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function A(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function kc(a,b,c,d){if(dc.length){var e=dc.pop();e.init(a,b,c,d);a=e}else a=new Qb(a,b,c,d);this.h=a;this.i=this.h.g;this.g=this.j=-1;this.setOptions(d)}kc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.R=a.R===void 0?!1:a.R};function lc(a,b,c,d){if(mc.length){var e=mc.pop();e.setOptions(d);e.h.init(a,b,c,d);return e}return new kc(a,b,c,d)}function nc(a){a.h.clear();a.j=-1;a.g=-1;mc.length<100&&mc.push(a)}
function oc(a){var b=a.h;if(b.g==b.i)return!1;a.i=a.h.g;var c=Ub(a.h);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw gb(c,a.i);if(b<1)throw Error("Invalid field number: "+b+" (at position "+a.i+")");a.j=b;a.g=c;return!0}
function pc(a){switch(a.g){case 0:a.g!=0?pc(a):$b(a.h);break;case 1:a=a.h;Sb(a,a.g+8);break;case 2:if(a.g!=2)pc(a);else{var b=Ub(a.h);a=a.h;Sb(a,a.g+b)}break;case 5:a=a.h;Sb(a,a.g+4);break;case 3:b=a.j;do{if(!oc(a))throw Error("Unmatched start-group tag: stream EOF");if(a.g==4){if(a.j!=b)throw Error("Unmatched end-group tag");break}pc(a)}while(1);break;default:throw gb(a.g,a.i);}}
function qc(a,b,c){var d=a.h.i,e=Ub(a.h),f=a.h.g+e,g=f-d;g<=0&&(a.h.i=f,c(b,a,void 0,void 0,void 0),g=f-a.h.g);if(g)throw Error("Message parsing ended unexpectedly. Expected to read "+(e+" bytes, instead read "+(e-g)+" bytes, either the data ended unexpectedly or the message misreported its own length"));a.h.g=f;a.h.i=d;return b}
function rc(a){var b=Ub(a.h);a=a.h;var c=bc(a,b);a=a.h;if(nb){var d=a,e;(e=mb)||(e=mb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(lb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),lb=!0}catch(n){lb=!1}}!lb&&(mb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?jb():(k=a[f++],h<194||(k&192)!==128?(f--,jb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?jb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,jb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?jb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,jb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):jb(),c.length>=8192&&(g=kb(g,c),c.length=0);f=kb(g,c)}return f}function sc(a){var b=Ub(a.h);return cc(a.h,b)}
function tc(a,b,c){var d=Ub(a.h);for(d=a.h.g+d;a.h.g<d;)c.push(b(a.h))}var mc=[];function uc(){this.i=[];this.h=0;this.g=new fc}function vc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function wc(a,b){B(a,b,2);b=a.g.end();vc(a,b);b.push(a.h);return b}function xc(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){ic(a.g,b*8+c)}function yc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),jc(a.g,c))}function zc(a,b,c){B(a,b,2);ic(a.g,c.length);vc(a,a.g.end());vc(a,c)}
function Ac(a,b,c,d){c!=null&&(b=wc(a,b),d(c,a),xc(a,b))}function Bc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?ab(a.substring(1)):ab(a)}};var Cc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Dc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Ec=Dc("jas",void 0,!0),Fc=Dc(void 0,"1oa"),Gc=Dc(void 0,Symbol()),Hc=Dc(void 0,"0ubs"),Ic=Dc(void 0,"0ubsb"),Jc=Dc(void 0,"0actk"),Kc=Dc("m_m","ba",!0);var Lc={aa:{value:0,configurable:!0,writable:!0,enumerable:!1}},Mc=Object.defineProperties,D=Cc?Ec:"aa",Nc,Oc=[];E(Oc,7);Nc=Object.freeze(Oc);function Pc(a,b){Cc||D in a||Mc(a,Lc);a[D]|=b}function E(a,b){Cc||D in a||Mc(a,Lc);a[D]=b};var Qc={};function Rc(a,b){return b===void 0?a.g!==Sc&&!!(2&(a.l[D]|0)):!!(2&b)&&a.g!==Sc}var Sc={};function Tc(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var Uc={};function Vc(a){return a&128?Uc:void 0};function Wc(a){return a};var Xc=void 0;function Yc(a,b){if(a!=null){var c;var d=(c=Xc)!=null?c:Xc={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",sb(a))}};function Zc(a){return Array.prototype.slice.call(a)};var $c=typeof BigInt==="function"?BigInt.asIntN:void 0,ad=typeof BigInt==="function"?BigInt.asUintN:void 0,bd=Number.isSafeInteger,cd=Number.isFinite,dd=Math.trunc;function id(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function jd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function kd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var ld=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function md(a){switch(typeof a){case "bigint":return!0;case "number":return cd(a);case "string":return ld.test(a);default:return!1}}function nd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return cd(a)?a|0:void 0}
function od(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return cd(a)?a>>>0:void 0}function pd(a){if(a[0]==="-")return!1;var b=a.length;return b<20?!0:b===20&&Number(a.substring(0,6))<184467}function qd(a){if(a<0){Pa(a);var b=Ua(v,y);a=Number(b);return bd(a)?a:b}b=String(a);if(pd(b))return b;Pa(a);return Ta(v,y)}
function rd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String($c(64,a));if(md(a)){if(b==="string")return b=dd(Number(a)),bd(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&Number(a.substring(0,7))>-922337:b<19||b===19&&Number(a.substring(0,6))<922337)||(Xa(a),a=v,b=y,b&2147483648?Fa()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Qa(a,b)),a=b.next().value,b=b.next().value,a="-"+Ua(a,b)):a=Ua(a,b))),a;if(b==="number")return a=
dd(a),bd(a)||(Pa(a),a=Va(v,y)),a}}function sd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(ad(64,a));if(md(a)){if(b==="string")return b=dd(Number(a)),bd(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),pd(a)||(Xa(a),a=Ua(v,y))),a;if(b==="number")return a=dd(a),a>=0&&bd(a)?a:qd(a)}}function td(a){if(a==null||typeof a=="string"||a instanceof Ib)return a}function ud(a){if(a!=null&&typeof a!=="string")throw Error();return a}
function vd(a){return a==null||typeof a==="string"?a:void 0};function wd(a){var b=Ca(Gc);return b?a[b]:void 0}function xd(){}function yd(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function zd(a){var b=new xd;yd(a,function(c,d,e){b[d]=Zc(e)});b.g=a.g;return b}function Ad(a,b){b<100||Yc(Hc,1)};function Bd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ca(Gc),g;!e&&Cc&&f&&(g=a[f])&&yd(g,Ad);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var x;g=((x=Cd)!=null?x:Wc)(g-n,n,a,w,void 0)+n}}b=void 0;for(x=0;x<h;x++){var z=a[x];if(z!=null&&(z=c(z,d))!=null)if(m&&x>=g){var G=x-n,C=void 0;((C=b)!=null?C:b={})[G]=z}else f[x]=z}if(w)for(var S in w)h=w[S],h!=
null&&(h=c(h,d))!=null&&(x=+S,z=void 0,m&&!Number.isNaN(x)&&(z=x+n)<g?f[z]=h:(x=void 0,((x=b)!=null?x:b={})[S]=h));b&&(k?f.push(b):f[g]=b);e&&Ca(Gc)&&(a=wd(a))&&a instanceof xd&&(f[Gc]=zd(a));return f}
function Dd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Ga?a>=Ia&&a<=Ka:a[0]==="-"?La(a,Ha):La(a,Ja))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[D]|0;return a.length===0&&b&1?void 0:Bd(a,b,Dd)}if(a!=null&&a[Kc]===Qc)return Ed(a);if(a instanceof Ib){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Cb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=
String.fromCharCode.apply(null,d?b.subarray(d):b);b=btoa(c)}else{c===void 0&&(c=0);Ab();c=wb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var Cd;function Ed(a){a=a.l;return Bd(a,a[D]|0,Dd)};var Fd,Gd;function Hd(a){switch(typeof a){case "boolean":return Fd||(Fd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Gd||(Gd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Id(a,b,c){return a=F(a,b[0],b[1],c?1:2)}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");e=a[D]|0;if(Ea&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Jd();if(e&256)throw Error("farr");if(e&64)return d!==0||e&2048||E(a,e|2048),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-8380417|(g&1023)<<13;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-8380417|(k&1023)<<13}}}e|=64;d===0&&(e|=2048);E(a,e);return a}function Jd(){if(Ea)throw Error("carr");Yc(Jc,5)};function Kd(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[D]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Ld(a,c,!1,b&&!(c&16)):(Pc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Kc]===Qc)return b=a.l,c=b[D]|0,Rc(a,c)?a:Md(a,b,c)?Nd(a,b):Ld(b,c);if(a instanceof Ib)return a}function Nd(a,b,c){a=new a.constructor(b);c&&(a.g=Sc);a.h=Sc;return a}function Ld(a,b,c,d){d!=null||(d=!!(34&b));a=Bd(a,b,Kd,d);d=32;c&&(d|=2);b=b&8380609|d;E(a,b);return a}
function Od(a){if(a.g!==Sc)return!1;var b=a.l;b=Ld(b,b[D]|0);Pc(b,2048);a.l=b;a.g=void 0;a.h=void 0;return!0}function Pd(a){if(!Od(a)&&Rc(a,a.l[D]|0))throw Error();}function Qd(a,b){b===void 0&&(b=a[D]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Md(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=Sc,!0):!1};function Rd(a,b,c){a=Sd(a.l,b,void 0,c);if(a!==null)return a}function Sd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function Td(a,b,c){Pd(a);var d=a.l;H(d,d[D]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[D]|0)>>13&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function Ud(a,b){return Vd(a,a[D]|0,b)}
function Wd(a){return a==null?a:typeof a==="string"?a?new Ib(a,Hb):Kb():a.constructor===Ib?a:Bb&&a!=null&&a instanceof Uint8Array?a.length?new Ib(new Uint8Array(a),Hb):Kb():void 0}function Vd(a,b,c){if(b&2)throw Error();var d=Vc(b);var e=Sd(a,c,d);e=Array.isArray(e)?e:Nc;var f=e===Nc?7:e[D]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||2&g&&4&g||256&g||16&g)e=Zc(e),f=0,g=Xd(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function Yd(a,b,c,d){Pd(a);var e=a.l,f=e[D]|0;if(d==null){var g=Zd(e);if($d(g,e,f,c)===b)g.set(c,0);else return a}else f=ae(e,f,c,b);H(e,f,b,d);return a}function be(a,b,c,d){var e=a[D]|0,f=Vc(e);e=ae(a,e,c,b,f);H(a,e,b,d,f)}function Zd(a){if(Cc){var b;return(b=a[Fc])!=null?b:a[Fc]=new Map}if(Fc in a)return a[Fc];b=new Map;Object.defineProperty(a,Fc,{value:b});return b}function ae(a,b,c,d,e){var f=Zd(a),g=$d(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function $d(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Sd(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function ce(a,b,c){var d=a[D]|0,e=Vc(d),f=Sd(a,c,e);if(f!=null&&f[Kc]===Qc){if(!Rc(f))return Od(f),f.l;var g=f.l}else Array.isArray(f)&&(g=f);if(g){var h=g[D]|0;h&2&&(g=Ld(g,h))}g=Id(g,b,!0);g!==f&&H(a,d,c,g,e);return g}
function de(a,b){var c=ee,d=!1,e=Sd(a,4,void 0,function(f){if(f!=null&&f[Kc]===Qc)var g=f;else if(Array.isArray(f)){g=f[D]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!Rc(e)&&Qd(a,b),e}function fe(a){var b=a.l,c=b[D]|0,d=de(b,c);if(d==null)return d;c=b[D]|0;if(!Rc(a,c)){var e=d;var f=e.l,g=f[D]|0;e=Rc(e,g)?Md(e,f,g)?Nd(e,f,!0):new e.constructor(Ld(f,g,!1)):e;e!==d&&(Od(a)&&(b=a.l,c=b[D]|0),d=e,c=H(b,c,4,d),Qd(b,c))}return d}
function ge(a){a==null&&(a=void 0);return a}function he(a,b,c){c=ge(c);Td(a,b,c);c&&!Rc(c)&&Qd(a.l);return a}function ie(a,b){Pd(a);var c=a.l,d=c[D]|0;if(b==null)return H(c,d,1),a;for(var e=b===Nc?7:b[D]|0,f=e,g=!!(2&e)&&!!(4&e)||!!(256&e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=Rc(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=Zc(b),f=0,e=Xd(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||Qd(c,d);return a}
function Xd(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.l=F(a,b,c)}I.prototype.toJSON=function(){var a=Ed(this);return a};I.prototype[Kc]=Qc;I.prototype.toString=function(){return this.l.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var je=J(),ke=J(),le=J(),me=J(),ne=J(),oe=J(),pe=J(),qe=J(),re=J(),se=J();function te(a,b,c){this.g=a;this.h=b;a=Ca(je);this.i=!!a&&c===a||!1}function ue(a,b){var c=c===void 0?je:c;return new te(a,b,c)}function ve(a,b,c,d,e){Ac(a,c,we(b,d),e)}var xe=ue(function(a,b,c,d,e){if(a.g!==2)return!1;qc(a,ce(b,d,c),e);return!0},ve),ye=ue(function(a,b,c,d,e){if(a.g!==2)return!1;qc(a,ce(b,d,c),e);return!0},ve),ze=Symbol(),Ae=Symbol(),Be=Symbol(),Ce=Symbol(),De=Symbol(),Ee,Fe;
function Ge(a,b,c,d){var e=d[a];if(e)return e;e={};e.Z=d;e.I=Hd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.S=f,f=d[++g],typeof f==="function"&&(e.X=!0,Ee!=null||(Ee=f),Fe!=null||(Fe=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof te)var n=f;else n=xe,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var x=h[k];m?c(e,k,n,m,x):b(e,k,n,x)}}return d[a]=e}function He(a){return Array.isArray(a)?a[0]instanceof te?a:[ye,a]:[a,void 0]}function we(a,b){if(a instanceof I)return a.l;if(Array.isArray(a))return Id(a,b,!1)};function Ie(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Je(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Ge(Ae,Ie,Je,d).I),g||(g=Ke(d)),e)}}
function Ke(a){var b=a[Be];if(b!=null)return b;var c=Ge(Ae,Ie,Je,a);b=c.X?function(d,e){return Ee(d,e,c)}:function(d,e){for(;oc(e)&&e.g!=4;){var f=e.j,g=c[f];if(g==null){var h=c.S;h&&(h=h[f])&&(h=Le(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.i;pc(h);if(h.R)var k=void 0;else{var m=h.h.g-g;h.h.g=g;k=cc(h.h,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Gc])!=null?m:n[Gc]=new xd)[f])!=null?g:h[f]=[]).push(k)}}if(d=wd(d))d.g=c.Z[De];return!0};a[Be]=b;a[De]=Me.bind(a);return b}
function Me(a,b,c,d){var e=this[Ae],f=this[Be],g=Id(void 0,e.I,!1),h=wd(a);if(h){var k=!1,m=e.S;if(m){e=function(G,C,S){if(S.length!==0)if(m[C])for(G=q(S),C=G.next();!C.done;C=G.next()){C=lc(C.value);try{k=!0,f(g,C)}finally{nc(C)}}else d==null||d(a,C,S)};if(b==null)yd(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[D]|0;if(w&2&&w&2048&&(c==null||!c.da))throw Error();var x=Vc(w),z=function(G,C){if(Sd(a,G,x)!=null)switch(c==null?void 0:c.ca){case 1:return;default:throw Error();}C!=null&&
(w=H(a,w,G,C,x));delete h[G]};b==null?Tc(g,g[D]|0,function(G,C){z(G,C)}):z(b,Sd(g,b,x))}}}}function Le(a){a=He(a);var b=a[0].g;if(a=a[1]){var c=Ke(a),d=Ge(Ae,Ie,Je,a).I;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Ne(a,b,c){a[b]=c.h}function Oe(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Ge(ze,Ne,Oe,d).I),e||(e=Pe(d)))}}function Pe(a){var b=a[Ce];if(!b){var c=Ge(ze,Ne,Oe,a);b=function(d,e){return Qe(d,e,c)};a[Ce]=b}return b}function Qe(a,b,c){Tc(a,a[D]|0,function(d,e){if(e!=null){var f=Re(c,d);f?f(b,e,d):d<500||Yc(Ic,3)}});(a=wd(a))&&yd(a,function(d,e,f){vc(b,b.g.end());for(d=0;d<f.length;d++)vc(b,Nb(f[d])||new Uint8Array(0))})}
function Re(a,b){var c=a[b];if(c)return c;if(c=a.S)if(c=c[b]){c=He(c);var d=c[0].h;if(c=c[1]){var e=Pe(c),f=Ge(ze,Ne,Oe,c).I;c=a.X?Fe(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[D]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);c&&(E(b,(d|5)&-1537),d&2&&Object.freeze(b));return b}}function L(a,b,c){return new te(a,b,c)}function M(a,b,c){return new te(a,b,c)}function N(a,b,c){H(a,a[D]|0,b,c,Vc(a[D]|0))}
var Se=ue(function(a,b,c,d,e){if(a.g!==2)return!1;a=qc(a,Id([void 0,void 0],d,!0),e);d=b[D]|0;e=Vc(d);if(d&2)throw Error();var f=Sd(b,c,e);if(Array.isArray(f)){if((f[D]|0)&2){f=Zc(f);for(var g=0;g<f.length;g++){var h=f[g]=Zc(f[g]);if(Array.isArray(h[1])){var k=h[1];Pc(k,34);h[1]=k}}H(b,d,c,f,e)}f.push(a)}else H(b,d,c,[a],e);return!0},function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Ac(a,c,Id(g,d,!1),e)}});
function Te(a,b,c){b=jd(b);b!=null&&(B(a,c,1),a=a.g,Sa(b),A(a,v),A(a,y))}function Ue(a,b,c){b=jd(b);b!=null&&(B(a,c,5),a=a.g,Ra(b),A(a,v))}function Ve(a,b,c){b=rd(b);if(b!=null){switch(typeof b){case "string":eb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Pa(b);hc(a,v,y);break;case "bigint":c=db(b);hc(a.g,c.h,c.g);break;default:c=eb(b),hc(a.g,c.h,c.g)}}}
function We(a,b,c){b=sd(b);if(b!=null){switch(typeof b){case "string":ab(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Pa(b);hc(a,v,y);break;case "bigint":c=$a(b);hc(a.g,c.h,c.g);break;default:c=ab(b),hc(a.g,c.h,c.g)}}}function Xe(a,b,c){b=nd(b);b!=null&&b!=null&&(B(a,c,0),jc(a.g,b))}function Ye(a,b,c){b=kd(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function Ze(a,b,c){b=vd(b);b!=null&&zc(a,c,rb(b))}function $e(a,b,c,d,e){Ac(a,c,we(b,d),e)}function af(a,b,c){yc(a,c,nd(b))}
function bf(a,b,c){if(a.g!==5&&a.g!==2)return!1;b=Ud(b,c);a.g==2?tc(a,Yb,b):b.push(Yb(a.h));return!0}function cf(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=Ud(b,c);a.g==2?tc(a,Tb,b):b.push(Tb(a.h));return!0}function df(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=Ud(b,c);a.g==2?tc(a,$b,b):b.push($b(a.h));return!0}
var ef=L(function(a,b,c,d){if(a.g!==1)return!1;be(b,c,d,Zb(a.h));return!0},Te,qe),O=L(function(a,b,c){if(a.g!==5)return!1;N(b,c,Yb(a.h));return!0},Ue,pe),ff=M(bf,function(a,b,c){b=K(jd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Ra(g),A(e,v))}},pe),gf=M(bf,function(a,b,c){b=K(jd,b,!0);if(b!=null&&b.length)for(B(a,c,2),ic(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Ra(b[c]);A(d,v)}},pe),hf=L(function(a,b,c,d){if(a.g!==5)return!1;be(b,c,d,Yb(a.h));return!0},
Ue,pe),jf=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Wb(a.h));return!0},Ve,ne),kf=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=Ud(b,c);a.g==2?tc(a,Wb,b):b.push(Wb(a.h));return!0},function(a,b,c){b=K(rd,b,!1);if(b!=null&&b.length){c=wc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.g;Pa(e);hc(f,v,y);break;case "bigint":e=db(e);hc(a.g,e.h,e.g);break;default:e=eb(e),hc(a.g,e.h,e.g)}}xc(a,c)}},ne),lf=L(function(a,b,c,d){if(a.g!==0)return!1;be(b,c,d,Wb(a.h));return!0},
Ve,ne),mf=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Rb(a.h,Ua));return!0},We,oe),nf=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Rb(a.h,Ta));return!0},We,oe),P=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Tb(a.h));return!0},Xe,me),of=M(cf,function(a,b,c){b=K(nd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),jc(e.g,g))}},me),pf=M(cf,function(a,b,c){b=K(nd,b,!0);if(b!=null&&b.length){c=wc(a,c);for(var d=0;d<b.length;d++)jc(a.g,b[d]);xc(a,c)}},me),qf=L(function(a,
b,c,d){if(a.g!==0)return!1;be(b,c,d,Tb(a.h));return!0},Xe,me),Q=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,$b(a.h));return!0},Ye,ke),rf=M(df,function(a,b,c){b=K(kd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},ke),sf=M(df,function(a,b,c){b=K(kd,b,!0);if(b!=null&&b.length)for(B(a,c,2),ic(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},ke),tf=L(function(a,b,c,d){if(a.g!==0)return!1;be(b,c,d,$b(a.h));return!0},Ye,ke),uf=L(function(a,b,
c,d){if(a.g!==2)return!1;be(b,c,d,rc(a));return!0},Ze,le),R=L(function(a,b,c){if(a.g!==2)return!1;N(b,c,rc(a));return!0},Ze,le),T=M(function(a,b,c){if(a.g!==2)return!1;a=rc(a);Vd(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(vd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&zc(e,f,rb(g))}},le),U,vf=void 0;vf=vf===void 0?je:vf;
U=new te(function(a,b,c,d,e){if(a.g!==2)return!1;d=Id(void 0,d,!0);Vd(b,b[D]|0,c).push(d);qc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)$e(a,b[f],c,d,e)},vf);
var V=ue(function(a,b,c,d,e,f){if(a.g!==2)return!1;var g=b[D]|0;ae(b,g,f,c,Vc(g));b=ce(b,d,c);qc(a,b,e);return!0},$e),wf=L(function(a,b,c){if(a.g!==2)return!1;N(b,c,sc(a));return!0},function(a,b,c){b=td(b);b!=null&&zc(a,c,Pb(b,!0).buffer)},re),W=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Ub(a.h));return!0},function(a,b,c){b=od(b);b!=null&&b!=null&&(B(a,c,0),ic(a.g,b))},J()),X=L(function(a,b,c){if(a.g!==0)return!1;N(b,c,Tb(a.h));return!0},af,se),xf=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=
Ud(b,c);a.g==2?tc(a,ac,b):b.push(Tb(a.h));return!0},function(a,b,c){b=K(nd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)yc(a,c,b[d])},se),Y=L(function(a,b,c,d){if(a.g!==0)return!1;be(b,c,d,Tb(a.h));return!0},af,se),yf=M(function(a,b,c){if(a.g!==0&&a.g!==2)return!1;b=Ud(b,c);a.g==2?tc(a,Vb,b):b.push(Vb(a.h));return!0},function(a,b,c){b=K(nd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),ic(e.g,(g<<1^g>>31)>>>0))}},J()),zf=[!0,R,P],Af=[!0,R,Q],Bf=[!0,R,R];function Cf(a){return function(b){var c=new uc;Qe(b.l,c,Ge(ze,Ne,Oe,a));vc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Df=[0,L(function(a,b,c){if(a.g!==1)return!1;var d=a.h;a=Xb(d);d=Xb(d);N(b,c,Ua(a,d));return!0},function(a,b,c){b=sd(b);if(b!=null)switch(Bc(b),B(a,c,1),a=a.g,Bc(b),typeof b){case "number":b<0?(c=-b,c=Za(new Ya(c&4294967295,c/4294967296)),b=c.g,A(a,c.h),A(a,b)):(Oa(b),A(a,v),A(a,y));break;case "bigint":c=b<BigInt(0)?Za($a(-b)):$a(b);b=c.g;A(a,c.h);A(a,b);break;default:c=b.length&&b[0]==="-"?Za(ab(b.substring(1))):ab(b),b=c.g,A(a,c.h),A(a,b)}},J()),-1];var Ef=[0,L(function(a,b,c){if(a.g!==5)return!1;a=a.h;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Sb(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=nd(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Ff=[0,X,-1,jf,R,Ef,-1,O,P,X,Df,R,X,-1,[0,Ef,-1],P,nf,Df,O,[0,1,P,-4,L(function(a,b,c){if(a.g!==1)return!1;N(b,c,Zb(a.h));return!0},Te,qe),[0,O,-1,P],R,O,U,[0,X,P],P,-1,X,-2,O,-1,X,O,X,P,[0,3,P,-1,1,W,-1,P,M(function(a,b,c){if(a.g!==2)return!1;a=sc(a);Vd(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(td,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&zc(e,f,Pb(g,!0).buffer)}},re)]],R,xf,U,[0,Df,U,[0,R,X],O,X,-1],1,U,[0,nf,-1,W],X,Df];var Gf=[0,jf,[0,O,R,P,R,P,of,jf,R,P,R,-1,O,P,O],wf,[0,M(function(a,b,c){if(a.g!==1&&a.g!==2)return!1;b=Ud(b,c);if(a.g==2){c=a.h;a=Ub(a.h)/8;var d=c.g,e=8*a;if(d+e>c.i)throw ib(e,c.i-d);var f=c.h;d+=f.byteOffset;ec===void 0&&(ec=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(ec)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(Zb(c))}else b.push(Zb(a.h));return!0},function(a,b,c){b=K(jd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Sa(g),A(e,v),A(e,y))}},qe),-1]];function ee(a){this.l=F(a)}p(ee,I);function Hf(a){a=Rd(a,1,Wd);return a==null?Kb():a}function If(a){var b=16E3;b=b===void 0?0:b;a=nd(Rd(a,2));return a!=null?a:b};function Jf(a){this.l=F(a)}p(Jf,I);function Kf(a){this.l=F(a)}p(Kf,I);var Lf=[0,wf,P];var Mf=[0,[1,2,3,4],uf,Y,V,[0,R,X],Y];var Nf=[0,R,-5,O,R,T,X,-1,U,Mf,R,-2];var Of=[0,P,-3];var Pf=[0,[1,2,3,4],tf,-1,uf,-1];var Qf=[0,R,-1,1,R,-1,6,T,[0,W,R,W,P,W,-4,O,W,O,-1],Q,T,-1];var Z=[0,X,-5];var Tf=[0,[0,R,-5,Q,T,Z],R,-7,Q,R,T,Z];var Uf=[0,T,1,X,-1,R];var Vf=[0,R,-2,Z,R];var Wf=[0,R,-1,Q,R,T,Z];var Xf=[0,U,[0,R,-1],R,Q,R];var Yf=[0,R,-2,Z];var Zf=[0,R,-3,P,R,Q,R,-1,Q,R,T,Z,R,-2];var $f=[0,Q,R,-3,P,R,Q,R,T,Z];var ag=[0,R,-3,P,R,-3,Q,R,T,Z];var bg=[0,R,P,X,R];var cg=[0,R,-2,P,R,Q,R,Q,T,Z];var dg=[0,R,-2,Q];var eg=[0,$f,cg,Wf,R,P,R,Q,R,T,Z];var fg=[0,$f,jf,R,P,R,Q,R,T,Z,R];var gg=[0,R,-1,Q,R,T,Z,Q];var hg=[0,R,P,Q];var ig=[0,R,T,R,P,R,Q,R,T,Z];var jg=[0,P,-2,Q,R,P,R,P,R,Q,R,T,Z,Q];var kg=[0,X,-1];var lg=[0,O,-1];var mg=[0,U,[0,O,-2],O,-1,P,U,[0,P,X,P,X,W,X,-1,U,lg,[0,O,-1],[0,U,lg,O,X],[0,U,lg,X]],O];var ng=[0,O,-2];var og=[-11,{},Of,R,[0,sf,pf,gf,T,U,[0,gf],[0,gf]],gf,R,-1,[0,ng],R,[0,gf,-1,U,[0,X,P]],-1];var pg=[0,Of,[0,Q,O,gf,-1],P,[0,gf]];var qg=[0,X,[0,of,kf]];var rg=[0,X,[0,of,T]];var sg=[0,P,-1,X,P];var tg=[0,gf,pf];var ug=[0,[0,mf,X,Q]];var vg=[0,P,-2,R];var wg=[0,X];var yg=[-15,{},U,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],uf,R,V,Wf,V,gg,V,$f,V,cg,V,jg,V,eg,V,Zf,V,Tf,V,ig,V,fg,V,ag,V,Xf,uf,-1,U,dg,uf,-1,mg,hf,[0,Q,-1,X,kg,Q,-1,O,Q,T,sg,X,-1],Ff,Q,V,[0,R,-1],U,[0,R,-1],[0,T,Q],Z,X,wg,Q,V,hg,R,T,R,V,Yf,V,Vf,R,-1,Q,V,bg,Q,vg,R],U,[0,R,U,[0,R,-1,X],U,[0,R,-1],R,X,[0,X,-3],T,Q,R],4,wg,O,Q,function(){return xg},R,ug,Q,[0,Q,-1]],xg=[0,U,function(){return yg},-1];var zg=function(a,b){return function(c,d){var e={L:!0};d&&Object.assign(e,d);c=lc(c,void 0,void 0,e);try{var f=new a,g=f.l;Ke(b)(g,c);var h=f}finally{nc(c)}return h}}(Kf,[0,X,2,Lf,X,[-500,{},nf,R,yg,-1,1,[0,X,P,-1,O],[0,R,-5,P,R,1,Q,-1,R,X,U,Nf,R],jf,-2,89,[-5,{},U,[-75,{},Of,W,-1,R,X,R,-2,Q,O,X,R,Q,-1,5,Wf,gg,R,$f,cg,jg,eg,$f,Zf,Tf,ig,fg,ag,R,-1,Yf,R,Vf,1,Xf,bg,[0,R,-1],U,dg,7,Qf,1,R,Q,R,Q,hg,R,Q,R,-2,Pf,R,Q,O,T,1,R,Q,1,R,Uf,X,Q],U,[-71,{},Of,X,R,-1,Q,1,R,X,Qf,O,X,Q,xf,R,kg,1,P,Q,1,R,X,O,[0,[0,O,
-2],[0,O,-2]],[0,X,-2],25,mg,R,3,Q,-1,1,Q,R,2,Q,Pf,R,X,O,R,-1,1,R],U,[-11,{},Of,R,X,5,[0,P,-3],R],U,[-12,{},Of,R,Q,O,-1,[0,O,-6,U,[0,R,X,O]],ff,P,-1,R,[0,[0,P,-3],U,[0,R,O]]]],1,[0,3,U,[0,U,[0,P,-2]],Q],3,sg,X,-1,1,[-8,{},sg,X,-1,[0,X,2,X,-1],X,-1,R],39,[0,[0,P,-2,pf,-2],rg,-2,qg,rg,-2,qg,-5],49,[-3,{},[0,U,og,[0,U,[0,R,U,[0,P,O,U,[0,P,O,-1,P],Q],U,[0,P,O],Q,-2]]],U,[0,P,U,[0,Of,[-10,{},P,-2,W,[0,W,-2,O,-8,ff,-5,yf,-1],xf,P,-2],ng,O,-2,U,[0,X,ff]]]],[-3,{},[0,U,og],U,[-6,{},U,pg,U,ng,of,rf,pf]],48,
[0,[0,U,pg,Gf],[0,O,W,-1,O,W]],49,Lf,599,[-1,{}],Q,[0,O,-2,P],[-3,{},U,[-7,{},W,-1,Q,U,[0,[1,2,3,4],V,[-5,{},X,R,-1,Q],V,[0],V,[0],V,[0]],O,W],W],tg]]);var Ag=Cf(Nf);function Bg(a){this.l=F(a)}p(Bg,I);var Cg=[1,4];function Dg(a){this.l=F(a,11)}p(Dg,I);var Eg=[0,P,wf,X];var Fg=[-11,{},[0,U,[0,X,1,X],xf,Ff,T,U,[0,R,X,O,X],1,X,-1,Q],[0,R,-3,O,[0,P,R],xf,-1],[0,Cg,hf,[0,X],[0,2,X],Y,[0,Q,-1],O,X,-2],[0,1,O,U,[0,R,-1],xf,ug,P],Uf,[-1,{}],[0,[1,3],V,[0,[3,4],U,Mf,-1,qf,tf,U,Mf],R,uf],[0,[1,2,3,4,5,6,7,8,9,10,11],Y,-10],[0,[1,2],[3,4,5],V,Eg,V,tg,V,Eg,V,tg,V,[0,gf]],[0,[1],V,tg]];var Gg=[-3,{},R,Fg];function Hg(a){this.l=F(a)}p(Hg,I);function Ig(a){this.l=F(a,5)}p(Ig,I);function Jg(a){this.l=F(a)}p(Jg,I);var Kg=[2,3,4];var Lg=[0,R,-2];var Mg=[0,[3,4],R,-1,lf,ef,P,-1,R,-1];var Ng=[0,Kg,P,V,[-5,{},U,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],P,R,-1,Fg,U,[0,[4,5],P,R,-1,Y,uf,R,Fg,X],R,-1,vg,Q,90,uf,V,[0,R,X,[0,X,O,X]],V,[0,R],V,[0,R,P],V,[0,R,X],V,[0,R,-1],V,[0,R,X],V,Mg,V,[0,1,R],V,Lg,V,[0,T,X],V,[0,[5,6,7],P,-2,R,Y,-1,qf],V,[0,[5,6],P,-3,Y,qf],V,[0,[1,2],[4,5,6],V,Mg,V,Lg,R,Y,-1,qf],V,[0,[3,4],[8,9,10],P,-1,qf,uf,P,X,R,Y,-1,qf],V,[0,R,T,R],V,[0,[4,5,6],Mg,R,1,Y,-1,qf],V,[0,R,-3,P,R,-2],V,[0,R,X],V,[0,U,[0,R,-1],R,Q],V,[0,
R,-1]],Fg,U,[0,P,-1,Fg],Q],V,Gg,V,[0,[1,2],V,Eg,V,[0,R]]];var Og=[0,Se,Af,Se,zf,Se,Bf];function Pg(a){this.l=F(a,4)}p(Pg,I);var Qg=[-4,{},U,Ng,Fg,Og];function Rg(a){this.l=F(a,3)}p(Rg,I);var Sg=Cf([-3,{},U,yg,Qg]);function Tg(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.P={};this.N={};this.C={};this.O={};this.B={};this.Y=new TextEncoder;this.T="";this.U=null;this.V=0;this.H=[];this.G=this.u=this.D=this.j=!1;this.v=[];this.M=[];this.A=[];this.i=a;this.F=this.i.createGain()}aa=Tg.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return r(c,loadWasmTtsBindings(),2);case 2:return b.g=c.h,r(c,Ug(b),3);case 3:return r(c,Vg(b),4);case 4:return c.return(Wg(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,Xg(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,Yg(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?(d.g=2,d=void 0):d=r(d,b.init(b.extensionId),2),d;if(d.g!=4)return r(d,Zg(b,a),4);(c=d.h)&&$g(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function Zg(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=ah(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.g=4;break}g=f.value;bh(a,g);if(!g.remote||g.unloaded){k.g=3;break}h="/voices/"+g.fileId;k.i=5;return r(k,ch(a,h),7);case 7:d=!0;qa(k,3);break;case 5:ra(k);case 3:f=e.next();k.g=2;break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();dh(b);b.j=!1;b.D=!1;b.u=a;b.m&&(b.m.disconnect(),c={command:"clearBuffers"},b.m.port.postMessage(c));for(eh(b);b.M.length>0;)window.clearTimeout(b.M.pop());b.v=[];b.H.length=0;d.g=0})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();eh(a);a.u=!0;return r(b,a.i.suspend(),2)}a.j=!1;b.g=0})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.j)return b.return();a.u=!1;return a.D?r(b,a.i.resume(),2):(a.A.length===0&&fh(a),b.return(gh(a)))}a.j=!0;hh(a);b.g=0})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,r(k,c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?r(k,c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.T===d){k.g=4;break}k.i=5;return r(k,ih(c,d,!1),7);case 7:e=c.C[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=jh(c,g);var n=jh(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);qa(k,4);break;case 5:return ra(k),k.return(Promise.reject(Error("Voice is not available")));case 4:c.T=d;var x=b.lang;c.extensionId&&x&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:x});try{if(x=d,c.g&&a.length){var z=new Ig,G=new Hg;var C=Td(G,2,ud(a));var S=ie(z,[C]);var qh=new Bg,Lb=b.rate;var rh=Yd(qh,1,Cg,id(!Lb||Lb<.1||Lb>10?1:Lb));var Rf=b.pitch;m=Td(rh,6,id(Rf?Math.pow(2,
(Rf-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.F.gain.value=Math.min(Math.max(b.volume,0),1));n=new Pg;w=new Jg;z=S;z=ge(z);Yd(w,2,Kg,z);z&&!Rc(z)&&Qd(w.l);var sh=ie(n,[w]);var th=new Dg;var uh=he(th,3,m);var vh=he(sh,2,uh);var wh=new Rg;var xh=he(wh,2,vh);var ed=Array.from(new Uint8Array(Sg(xh))),yh=c.O[x],zh=new Jf;var Ah=Td(zh,1,ud(yh));var fd=Ag(Ah),gd=c.g._malloc(ed.length);c.g.HEAPU8.set(ed,gd);var hd=c.g._malloc(fd.length);c.g.HEAPU8.set(fd,hd);var Bh=c.g._GoogleTtsInitBuffered(gd,hd,
ed.length,fd.length);c.g._free(gd);c.g._free(hd);if(!Bh)throw Error("Failed to initialize buffered synthesis.");fh(c)}}catch(Sf){return h=Sf instanceof Error?Sf.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.g=0}})};
function Wg(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.G&&b.data.type==="empty"&&(kh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.F.connect(a.i.destination)})}function jh(a,b){b=a.Y.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function fh(a){var b=setTimeout(function(){a.G=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)kh(a,{type:"error"}),dh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)lh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=zg(c.slice(0,
e));d=d===0;e=c.l;de(e,e[D]|0)!==void 0?mh(a,c,d):nh(a,null);d?dh(a):fh(a)}},0);a.A.push(b)}function dh(a){a.G=!1;a.g._GoogleTtsFinalizeBuffered()}function eh(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function lh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.j?c<-100||(c<2?kh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.j?kh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.M.push(c))):a.v.push(b))}
function hh(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())lh(a,c.value)}function mh(a,b,c){if(If(fe(b))===24E3){var d;b=(d=Hf(fe(b)))==null?void 0:new Uint8Array(Nb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});oh(a,d,c)}}
function oh(a,b,c){for(var d=a.U,e=a.V,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(nh(a,d),e=0,d=null)}e!==0&&(c?nh(a,d):(a.U=d,a.V=e))}function nh(a,b){b&&a.H.push(b);if(a.m)for(;b=a.H.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.D||a.u||gh(a)}function gh(a){return t(function(b){if(b.g==1)return a.m.connect(a.F),r(b,a.i.resume(),2);a.j=!0;a.D=!0;kh(a,{type:"start",charIndex:0});hh(a);b.g=0})}
function Xg(a,b){return t(function(c){return c.return(ph(a,b,!1))})}function Yg(a,b){return t(function(c){return c.return(ph(a,b,!0))})}function ph(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=ah(a,b),e=d.map(function(h){return ih(a,h.speakers[0].name,c)}),g.i=2,r(g,Promise.all(e),4);case 4:f="installed";c&&$g(a);qa(g,3);break;case 2:ra(g),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function ah(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Ch(a,b,c){var d,e,f,g,h,k,m,n,w,x;return t(function(z){if(!a.B[b])return z.return(Promise.resolve());d=a.B[b];f=q(Object.entries(a.N));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,x=n,d===x){e=w;break}return e?z.return(ih(a,e,c)):z.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function ih(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.i=2;return r(m,Ch(a,b,c),4);case 4:qa(m,3);break;case 2:return d=ra(m),m.return(Promise.reject(Error(""+d)));case 3:e=a.C[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.P[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Dh(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(G){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=jh(a,f),x=new Uint8Array(n),z=a.g._malloc(x.length);a.g.HEAPU8.set(x,z);n=a.g._GoogleTtsInstallVoice(w,z,n.byteLength);a.g._free(w);a.g._free(z);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(G,C){a.g.FS.syncfs(!1,function(S){S?C(S):G()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function kh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function Ug(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.i=2;return r(d,new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return qa(d,0);c=ra(d);throw c;})}
function Vg(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.i=2,r(e,fetch("voices.json"),4);case 4:b=e.h;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return r(e,b.json(),5);case 5:c=e.h;a.o=c;$g(a);qa(e,0);break;case 2:throw d=ra(e),d;}})}
function $g(a){a.P={};a.N={};a.C={};a.O={};a.B={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.N[f.name]=d.id;a.C[f.name]=d.fileId;a.O[f.name]=f.speaker;d.dependentVoiceId&&(a.B[f.name]=d.dependentVoiceId);bh(a,d);a.P[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function bh(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function ch(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Dh(a,b,c){var d,e;return t(function(f){if(f.g==1)return r(f,Eh(c),2);d=f.h;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Eh(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?r(f,crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.h;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(Tg.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Fh=new Tg,Gh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Gh||(Gh=Fh.init(b.id));Gh.then(function(){switch(a.type){case "init":Fh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Fh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Fh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Fh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":Zg(Fh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Fh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Fh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Fh.onPause();c({result:"Paused speech"});break;case "resume":Fh.onResume(),c({result:"Resumed speech"})}});return!0});
