-- CreateEnum
CREATE TYPE "StatusVenda" AS ENUM ('QUALIFICANDO', 'INTERESSE_DEMONSTRADO', 'CONSULTA_AGENDADA', 'CONSULTA_REALIZADA', 'ORCAMENTO_ENVIADO', 'NEGOCIACAO', 'GANHO', 'PERDIDO', 'PAUSADO');

-- CreateEnum
CREATE TYPE "TipoEtapa" AS ENUM ('CAPTACAO', 'QUALIFICACAO', 'AGENDAMENTO', 'ATENDIMENTO', 'ORCAMENTO', 'NEGOCIACAO', 'FECHAMENTO', 'POS_VENDA');

-- AlterTable
ALTER TABLE "FunnelStep" ADD COLUMN     "corEtapa" TEXT,
ADD COLUMN     "iconEtapa" TEXT,
ADD COLUMN     "metaConversao" DOUBLE PRECISION,
ADD COLUMN     "tempoMedioEtapa" INTEGER,
ADD COLUMN     "tipoEtapa" "TipoEtapa" NOT NULL DEFAULT 'QUALIFICACAO',
ADD COLUMN     "valorMedioEtapa" DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "dataFechamento" TIMESTAMP(3),
ADD COLUMN     "dataOrcamento" TIMESTAMP(3),
ADD COLUMN     "probabilidadeFecho" INTEGER,
ADD COLUMN     "statusVenda" "StatusVenda" NOT NULL DEFAULT 'QUALIFICANDO',
ADD COLUMN     "valorDesconto" DECIMAL(65,30),
ADD COLUMN     "valorOrcamento" DECIMAL(65,30);
